# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20160214_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='front_page',
            field=models.NullBooleanField(),
        ),
    ]
