# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.TextField(null=True),
        ),
    ]
